// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'machine.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Machine _$MachineFromJson(Map<String, dynamic> json) => Machine(
      json['id'] as int,
      json['typeLutId'] as int?,
      json['actorId'] as int?,
      json['modelId'] as int?,
      json['profileLutId'] as int?,
      json['name'] as String?,
      json['number'] as String?,
      json['serialNumber'] as String?,
      json['smartStickerId'] as int?,
      json['deviceId'] as int?,
      json['deviceSerialNumber'] as String?,
      json['vposId'] as int?,
      json['vposSerialNumber'] as String?,
      json['groupId'] as int?,
      json['locationType'] as int?,
      json['subLocationType'] as int?,
      json['institute'] as int?,
      json['locationId'] as int?,
      json['customerLocationId'] as int?,
      json['customerLocation'] as String?,
      json['country'] as int?,
      json['region'] as int?,
      json['city'] as int?,
      json['zipCode'] as String?,
      json['timeZone'] as int?,
      (json['geoLongitude'] as num?)?.toDouble(),
      (json['geoLatitude'] as num?)?.toDouble(),
      json['geoAddress'] as String?,
      json['geoCountry'] as int?,
      json['geoState'] as String?,
      json['geoCity'] as String?,
      json['geoZipCode'] as String?,
      json['salesSourceLutId'] as int?,
      json['statusId'] as int?,
      json['remarks'] as String?,
      json['timeZoneKey'] as int?,
      json['operatorActorId'] as int?,
      json['monyxMachineId'] as int?,
    );

Map<String, dynamic> _$MachineToJson(Machine instance) => <String, dynamic>{
      'id': instance.id,
      'typeLutId': instance.typeLutId,
      'actorId': instance.actorId,
      'modelId': instance.modelId,
      'profileLutId': instance.profileLutId,
      'name': instance.name,
      'number': instance.number,
      'serialNumber': instance.serialNumber,
      'smartStickerId': instance.smartStickerId,
      'deviceId': instance.deviceId,
      'deviceSerialNumber': instance.deviceSerialNumber,
      'vposId': instance.vposId,
      'vposSerialNumber': instance.vposSerialNumber,
      'groupId': instance.groupId,
      'locationType': instance.locationType,
      'subLocationType': instance.subLocationType,
      'institute': instance.institute,
      'locationId': instance.locationId,
      'customerLocationId': instance.customerLocationId,
      'customerLocation': instance.customerLocation,
      'country': instance.country,
      'region': instance.region,
      'city': instance.city,
      'zipCode': instance.zipCode,
      'timeZone': instance.timeZone,
      'geoLongitude': instance.geoLongitude,
      'geoLatitude': instance.geoLatitude,
      'geoAddress': instance.geoAddress,
      'geoCountry': instance.geoCountry,
      'geoState': instance.geoState,
      'geoCity': instance.geoCity,
      'geoZipCode': instance.geoZipCode,
      'statusId': instance.statusId,
      'remarks': instance.remarks,
      'salesSourceLutId': instance.salesSourceLutId,
      'timeZoneKey': instance.timeZoneKey,
      'operatorActorId': instance.operatorActorId,
      'monyxMachineId': instance.monyxMachineId,
    };
